
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class DeleteEvent extends javax.swing.JFrame {
    public static LinkedList list1 = new LinkedList();
     //list1 = new LinkedList();
    /**
     * Creates new form DeleteEvent
     */
    public DeleteEvent() {
        initComponents();
     
        String line="";
        String msg="";
        //LinkedList list1 = new LinkedList();
        LoginForm HF = new LoginForm();
        System.out.println("FileName : "+HF.FileName);
        int eventCount=0;
        try {
            // TODO add your handling code here:
            BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\Hp\\Desktop\\Assistant\\test\\DataFiles\\"+HF.FileName));
            
            while((msg = br.readLine()) != null){
                line += msg + "\n";
                eventCount++;
            }
            br.close();
           // JOptionPane.showMessageDialog(null," "+line);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dName=this.delName.getText();
        
        
        String []str=line.split(" ");
        System.out.println("Total Events = "+eventCount);
            for(int i=0;i<eventCount*11;){
                System.out.print(str[i]+" ");
                System.out.print(str[i+1]+"/");
                System.out.print(str[i+2]+"/");
                System.out.print(str[i+3]+" ");
                System.out.print(str[i+4]+":");
                System.out.print(str[i+5]+" ");
                System.out.print(str[i+6]+"/");
                System.out.print(str[i+7]+"/");
                System.out.print(str[i+8]+" ");
                System.out.print(str[i+9]+" ");
                System.out.print(str[i+10]+" ");
        evtname=str[i];
        date=Integer.parseInt(str[i+1]);
        mnth=Integer.parseInt(str[i+2]);
        year=Integer.parseInt(str[i+3]);
        hr=Integer.parseInt(str[i+4]);
        min=Integer.parseInt(str[i+5]);
        edate=Integer.parseInt(str[i+6]);
        emnth=Integer.parseInt(str[i+7]);
        eyear=Integer.parseInt(str[i+8]);
        venName=str[i+9];
        
        if(str[i+10]=="true"){
            pri=true;
        }
        else{pri=false;}
        list1.create_Event(evtname,date,mnth,year,hr,min,edate,emnth,eyear,venName,pri);
        
                
                i=i+11;
            }/*
            list1.traverse_and_print_head();
            //list1.deleteEvent_byName(this.delName.getText());
            list1.traverse_and_print_head();
            list1.traverse_and_print_tail();
            */
            String []tabStr=line.split(" ");
            
            String lne="";
            for(int i=0;i<eventCount*11;){
        evtname=str[i];
        date=Integer.parseInt(str[i+1]);
        mnth=Integer.parseInt(str[i+2]);
        year=Integer.parseInt(str[i+3]);
        hr=Integer.parseInt(str[i+4]);
        min=Integer.parseInt(str[i+5]);
        edate=Integer.parseInt(str[i+6]);
        emnth=Integer.parseInt(str[i+7]);
        eyear=Integer.parseInt(str[i+8]);
        venName=str[i+9];
        
        if(str[i+10]=="true"){
            pri=true;
        }
        else{pri=false;}
        lne += evtname+"  "+edate+"/"+emnth+"/"+eyear+"  "+hr+" : "+min+"\n";
                
                i=i+11;
            }
            
            this.jTextPane1.setText(lne);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        delName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Search by Name");

        delName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delNameActionPerformed(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(" Back ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Note: Once you delete an event there will be no way to restore it");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Delete Panel");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(204, 255, 255)));

        jTextPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("inactiveCaption"));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Total Events:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(delName, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(delName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //int select= JOptionPane.showConfirmDialog(null,"Confirm to delete event!","ERROR",JOptionPane.YES_NO_OPTION);
         LinkedList list2 = new LinkedList();
        String line="";
        String msg="";
        //LinkedList list1 = new LinkedList();
        LoginForm HF = new LoginForm();
        System.out.println("FileName : "+HF.FileName);
        int eventCount=0;
        try {
            // TODO add your handling code here:
            BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\Hp\\Desktop\\Assistant\\test\\DataFiles\\"+HF.FileName));
            
            while((msg = br.readLine()) != null){
                line += msg + "\n";
                eventCount++;
            }
            br.close();
           // JOptionPane.showMessageDialog(null," "+line);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dName=this.delName.getText();
        
        
        String []str=line.split(" ");
        System.out.println("Total Events = "+eventCount);
            for(int i=0;i<eventCount*11;){
                System.out.print(str[i]+" ");
                System.out.print(str[i+1]+"/");
                System.out.print(str[i+2]+"/");
                System.out.print(str[i+3]+" ");
                System.out.print(str[i+4]+":");
                System.out.print(str[i+5]+" ");
                System.out.print(str[i+6]+"/");
                System.out.print(str[i+7]+"/");
                System.out.print(str[i+8]+" ");
                System.out.print(str[i+9]+" ");
                System.out.print(str[i+10]+" ");
        evtname=str[i];
        date=Integer.parseInt(str[i+1]);
        mnth=Integer.parseInt(str[i+2]);
        year=Integer.parseInt(str[i+3]);
        hr=Integer.parseInt(str[i+4]);
        min=Integer.parseInt(str[i+5]);
        edate=Integer.parseInt(str[i+6]);
        emnth=Integer.parseInt(str[i+7]);
        eyear=Integer.parseInt(str[i+8]);
        venName=str[i+9];
        
        if(str[i+10]=="true"){
            pri=true;
        }
        else{pri=false;}
        list2.create_Event(evtname,date,mnth,year,hr,min,edate,emnth,eyear,venName,pri);
        
                
                i=i+11;
            }/*
            list2.traverse_and_print_head();
            //list2.deleteEvent_byName(this.delName.getText());
            list2.traverse_and_print_head();
            list2.traverse_and_print_tail();
            */
            //this.jTextPane1.setText(line);
    
        list2.traverse_and_print_head();
        
        
        
        System.out.println("\n event name to be deleted "+this.delName.getText());
        String st=this.delName.getText();
       // st="Event_3";
      
        list2.deleteEvent_byName2(st);
        list2.sortSinlge(list2);
        list2.writeOnfile();
        JOptionPane.showMessageDialog(this,"Event has been deleted","Confirmation",JOptionPane.INFORMATION_MESSAGE);
        System.out.println("After deleteion");
        
        list2.traverse_and_print_head();
        dispose();
        new HomeForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //0list1.traverse_and_print_tail( /* Voice voce */ );
        dispose();
        new HomeForm().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void delNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delNameActionPerformed
        // TODO add your handling code here:
        ename=this.delName.getText();
    }//GEN-LAST:event_delNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField delName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
public static String ename;
    String evtname;
        int date;
        int mnth;
        int year;
        int hr;
        int min;
        int edate;
        int emnth;
        int eyear;
        String venName;
        private boolean pri;
}
