
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class EditForm extends javax.swing.JFrame {

    /**
     * Creates new form EditForm
     */
    public EditForm() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        editName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        editsYear = new javax.swing.JTextField();
        editsMonth = new javax.swing.JTextField();
        editsDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editvenueName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edithour = new javax.swing.JTextField();
        editminute = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editeDate = new javax.swing.JTextField();
        editeMonth = new javax.swing.JTextField();
        editeYear = new javax.swing.JTextField();
        editpriority = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editName.setText("Event");
        editName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Event Name");

        editsYear.setText("0000");

        editsMonth.setText("00");

        editsDate.setText("00");

        jLabel2.setText("Date dd/mm/yyyy");

        editvenueName.setText("Venue");
        editvenueName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editvenueNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Venue Name");

        jLabel3.setText("Start Time dd/mm");

        edithour.setText("00");
        edithour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edithourActionPerformed(evt);
            }
        });

        editminute.setText("00");

        jLabel4.setText("End date dd/mm/yyyy");

        editeDate.setText("00");

        editeMonth.setText("00");

        editeYear.setText("0000");
        editeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editeYearActionPerformed(evt);
            }
        });

        editpriority.setText("Get Notification");
        editpriority.setToolTipText("true");
        editpriority.setActionCommand("");
        editpriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpriorityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(editsDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editsMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editsYear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editeDate, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(edithour))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(editeMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(editminute, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editvenueName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(editpriority)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(editName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editsYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editsMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editsDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(editvenueName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edithour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editminute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editeMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editeYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editpriority))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ready to edit event");

        jButton1.setText(" Edit ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editvenueNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editvenueNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editvenueNameActionPerformed

    private void edithourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edithourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edithourActionPerformed

    private void editeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editeYearActionPerformed

    private void editpriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpriorityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_editpriorityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*
        editName.setText(LinkedList.EditeventName);
        editsDate.setText(LinkedList.Editdate);
        editsMonth.setText(LinkedList.Editmonth);
        editsYear.setText(LinkedList.Edityear);
        editvenueName.setText(LinkedList.EditvenueName);
        edithour.setText(LinkedList.Edithour);
        editminute.setText(LinkedList.Editminute);
        editeDate.setText(LinkedList.Editedate);
        editeMonth.setText(LinkedList.Editemonth);
        editeYear.setText(LinkedList.Editeyear);
        */
        String j="\n"+this.editName.getText();
        String []h = j.split(" ");
        String Nevtname=h[1];
        int Ndate=Integer.parseInt(this.editsDate.getText());
        int Nmnth=Integer.parseInt(this.editsMonth.getText());
        int Nyear=Integer.parseInt(this.editsYear.getText());
        int Nhr=Integer.parseInt(this.edithour.getText());
        int Nmin=Integer.parseInt(this.editminute.getText());
        int Nedate=Integer.parseInt(this.editeDate.getText());
        int Nemnth=Integer.parseInt(this.editeMonth.getText());
        int Neyear=Integer.parseInt(this.editeYear.getText());
        String NvenName=this.editvenueName.getText();
         LinkedList list2 = new LinkedList();
        String line="";
        String msg="";
        //LinkedList list1 = new LinkedList();
        LoginForm HF = new LoginForm();
        System.out.println("FileName : "+HF.FileName);
        int eventCount=0;
        try {
            // TODO add your handling code here:
            BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\Hp\\Desktop\\Assistant\\test\\DataFiles\\"+HF.FileName));
            
            while((msg = br.readLine()) != null){
                line += msg + "\n";
                eventCount++;
            }
            br.close();
           // JOptionPane.showMessageDialog(null," "+line);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
       // String dName=this.delName.getText();
        
        boolean pri;
        String []str=line.split(" ");
        System.out.println("Total Events = "+eventCount);
            for(int i=0;i<eventCount*11;){
                System.out.print(str[i]+" ");
                System.out.print(str[i+1]+"/");
                System.out.print(str[i+2]+"/");
                System.out.print(str[i+3]+" ");
                System.out.print(str[i+4]+":");
                System.out.print(str[i+5]+" ");
                System.out.print(str[i+6]+"/");
                System.out.print(str[i+7]+"/");
                System.out.print(str[i+8]+" ");
                System.out.print(str[i+9]+" ");
                System.out.print(str[i+10]+" ");
      
        
        if(str[i+10]=="true"){
            pri=true;
        }
        else{pri=false;}
        list2.create_Event(str[i],Integer.parseInt(str[i+1]),Integer.parseInt(str[i+2]),Integer.parseInt(str[i+3]),Integer.parseInt(str[i+4]),Integer.parseInt(str[i+5]),Integer.parseInt(str[i+6]),Integer.parseInt(str[i+7]),Integer.parseInt(str[i+8]),str[i+9],pri);
            i=i+11;
        }
    
        list2.traverse_and_print_head();
        
        
        
        System.out.println("\n event name to beEdited "+this.jTextField1.getText());
        String st=this.jTextField1.getText();
       // st="Event_3";
        //JOptionPane.showMessageDialog(this,"Event has been deleted","Confirmation",JOptionPane.INFORMATION_MESSAGE);
        System.out.println("After deleteion");
        
        if(editpriority.isSelected()){
            pri=true;
        }else{
            pri=false;
        }
        list2.create_Event("\n"+Nevtname, Ndate, Nmnth, Nyear, Nhr, Nmin, Nedate, Nemnth, Neyear, NvenName, pri);
        list2.traverse_and_print_head();
        list2.sortSinlge(list2);
        list2.traverse_and_print_head();
        list2.writeOnfile();
                
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        HomeForm HF = new HomeForm();
        HF.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         LinkedList list2 = new LinkedList();
        String line="";
        String msg="";
        //LinkedList list1 = new LinkedList();
        LoginForm HF = new LoginForm();
        System.out.println("FileName : "+HF.FileName);
        int eventCount=0;
        try {
            // TODO add your handling code here:
            BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\Hp\\Desktop\\Assistant\\test\\DataFiles\\"+HF.FileName));
            
            while((msg = br.readLine()) != null){
                line += msg + "\n";
                eventCount++;
            }
            br.close();
           // JOptionPane.showMessageDialog(null," "+line);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DeleteEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
       // String dName=this.delName.getText();
        
        boolean pri;
        String []str=line.split(" ");
        System.out.println("Total Events = "+eventCount);
            for(int i=0;i<eventCount*11;){
                System.out.print(str[i]+" ");
                System.out.print(str[i+1]+"/");
                System.out.print(str[i+2]+"/");
                System.out.print(str[i+3]+" ");
                System.out.print(str[i+4]+":");
                System.out.print(str[i+5]+" ");
                System.out.print(str[i+6]+"/");
                System.out.print(str[i+7]+"/");
                System.out.print(str[i+8]+" ");
                System.out.print(str[i+9]+" ");
                System.out.print(str[i+10]+" ");
      
        
        if(str[i+10]=="true"){
            pri=true;
        }
        else{pri=false;}
        list2.create_Event(str[i],Integer.parseInt(str[i+1]),Integer.parseInt(str[i+2]),Integer.parseInt(str[i+3]),Integer.parseInt(str[i+4]),Integer.parseInt(str[i+5]),Integer.parseInt(str[i+6]),Integer.parseInt(str[i+7]),Integer.parseInt(str[i+8]),str[i+9],pri);
        
                
                i=i+11;
            }
    
        list2.traverse_and_print_head();
        
        
        
        System.out.println("\n event name to be deleted "+this.jTextField1.getText());
        String st=this.jTextField1.getText();
       // st="Event_3";
      
        list2.search_byName2(st);
        list2.sortSinlge(list2);
        list2.writeOnfile();
        //JOptionPane.showMessageDialog(this,"Event has been deleted","Confirmation",JOptionPane.INFORMATION_MESSAGE);
        System.out.println("After deleteion");
        
        editName.setText(LinkedList.EditeventName);
        editsDate.setText(LinkedList.Editdate);
        editsMonth.setText(LinkedList.Editmonth);
        editsYear.setText(LinkedList.Edityear);
        editvenueName.setText(LinkedList.EditvenueName);
        edithour.setText(LinkedList.Edithour);
        editminute.setText(LinkedList.Editminute);
        editeDate.setText(LinkedList.Editedate);
        editeMonth.setText(LinkedList.Editemonth);
        editeYear.setText(LinkedList.Editeyear);
        
        
        
        String evtname=this.editName.getText();
        int date=Integer.parseInt(this.editsDate.getText());
        int mnth=Integer.parseInt(this.editsMonth.getText());
        int year=Integer.parseInt(this.editsYear.getText());
        int hr=Integer.parseInt(this.edithour.getText());
        int min=Integer.parseInt(this.editminute.getText());
        int edate=Integer.parseInt(this.editeDate.getText());
        int emnth=Integer.parseInt(this.editeMonth.getText());
        int eyear=Integer.parseInt(this.editeYear.getText());
        String venName=this.editvenueName.getText();
        
        
        
        if(editpriority.isSelected()){
            pri=true;
        }else{
            pri=false;
        }
        
        
        list2.create_Event(evtname, date, mnth, year, hr, min, edate, emnth, eyear, venName, pri);
        list2.sortSinlge(list2);
        list2.traverse_and_print_head();
                
                
        /*
        //System.out.println(""+pri);
        //new LinkedList().create_Event(venName, hr, mnth, year, hr, min, edate, emnth, eyear, venName, pri);
        list2.create_Event(evtname,date,mnth,year,hr,min,edate,emnth,eyear,venName,pri);
        try {
            // TODO add your handling code here:
            //close();
             LoginForm HF = new LoginForm();
        System.out.println("FileName : "+HF.FileName);
        
        BufferedWriter bw = new BufferedWriter(new FileWriter("C:\\Users\\Hp\\Desktop\\Assistant\\test\\DataFiles\\"+HF.FileName,true));
        bw.write(evtname+" "+date+" "+mnth+" "+year+" "+hr+" "+min+" "+edate+" "+emnth+" "+eyear+" "+venName+" "+pri+" "+System.lineSeparator());
        bw.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"Unable to open file.","Error!",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AddEvent.class.getName()).log(Level.SEVERE, null, ex);
            dispose();
        }
        AddEvent obj=new AddEvent();
        Thread tobj = new Thread(obj);
        tobj.start();
        
        JOptionPane.showMessageDialog(this,"Event has been created","Confirmation",JOptionPane.INFORMATION_MESSAGE);
        
        
        */
        
        
        
        
        

        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editName;
    private javax.swing.JTextField editeDate;
    private javax.swing.JTextField editeMonth;
    private javax.swing.JTextField editeYear;
    private javax.swing.JTextField edithour;
    private javax.swing.JTextField editminute;
    private javax.swing.JCheckBox editpriority;
    private javax.swing.JTextField editsDate;
    private javax.swing.JTextField editsMonth;
    private javax.swing.JTextField editsYear;
    private javax.swing.JTextField editvenueName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
